[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "loone_data_prep"
version = "0.1.3"
dependencies = ["rpy2", "retry", "pandas", "scipy", "geoglows>=0.27.1"]
